[settings]
experimental = true # Enable experimental features (ie hooks)

[hooks]
enter = 'echo "ENTER"'
leave = 'echo "LEAVE"'
cd = 'echo "CD"'

[tools]
go = "latest"
python = "latest"
node = "latest"
"ubi:go-task/task" = "latest"

[tasks."nixd/init"]
run = "echo 'command needed'"
[tasks."nixd/reload"]
run = "darwin-rebuild switch --flake ~/.config/nix#macos"